# Generated by Django 4.0.1 on 2022-01-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=True, unique=True, verbose_name='ID'),
        ),
    ]
